# Generated by Django 6.0.2 on 2026-02-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('ATTESTATION', 'Attestation de scolarité'), ('RELEVE', 'Relevé de notes')], max_length=20)),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demandé'), ('TRAITEMENT', 'En cours'), ('PRET', 'Prêt à récupérer')], default='DEMANDE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_precedentes', models.FileField(upload_to='justificatifs_notes/')),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_inscription', to=settings.AUTH_USER_MODEL)),
                ('filiere_souhaitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academique.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='DossierEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField()),
                ('annee_actuelle', models.CharField(default='2025-2026', max_length=9)),
                ('etudiant', models.OneToOneField(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_scolaire', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academique.filiere')),
            ],
        ),
    ]
