# Generated by Django 5.2.11 on 2026-02-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0003_alter_demandedocument_id_alter_demandeinscription_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandedocument',
            old_name='date_demande',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='demandedocument',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents_etudiants/'),
        ),
        migrations.AlterField(
            model_name='demandedocument',
            name='statut',
            field=models.CharField(choices=[('DEMANDE', 'Demandé'), ('PRET', 'Prêt / Disponible'), ('REJETE', 'Rejeté')], default='DEMANDE', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandedocument',
            name='type_document',
            field=models.CharField(choices=[('ATTESTATION', 'Attestation de Scolarité'), ('RELEVE', 'Relevé de Notes')], max_length=20),
        ),
    ]
