# Generated by Django 6.0.2 on 2026-02-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur (Direction Générale)'), ('RH', 'Responsable RH'), ('SCOLARITE', 'Agent de Scolarité'), ('PROFESSEUR', 'Professeur'), ('ETUDIANT', 'Étudiant'), ('CANDIDAT', 'Candidat (Externe)')], max_length=20, verbose_name='Rôle'),
        ),
    ]
