# Generated by Django 6.0.2 on 2026-04-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_photo_user_photo_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_urgent', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur (Direction Générale)'), ('RH', 'Responsable RH'), ('SCOLARITE', 'Agent de Scolarité'), ('PROFESSEUR', 'Professeur'), ('ETUDIANT', 'Étudiant'), ('CANDIDAT', 'Candidat (Externe)'), ('DIRECTEUR', 'Administrateur (Direction Générale)')], max_length=20, verbose_name='Rôle'),
        ),
    ]
