# Generated by Django 6.0.2 on 2026-02-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
        ('rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='professeur_principal',
            field=models.ForeignKey(limit_choices_to={'role': 'PROFESSEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filiere',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academique.cycle'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres_academiques', to='rh.departement'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='responsable',
            field=models.ForeignKey(limit_choices_to={'role': 'PROFESSEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cours',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academique.filiere'),
        ),
    ]
