# Generated by Django 6.0.2 on 2026-02-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0003_seance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_support', models.CharField(choices=[('COURS', 'Cours Magistral'), ('TD', 'Travaux Dirigés (TD)'), ('TP', 'Travaux Pratiques (TP)')], max_length=10)),
                ('fichier', models.FileField(upload_to='supports_cours/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='academique.cours')),
            ],
        ),
    ]
