# Generated by Django 6.0.2 on 2026-02-04 21:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0005_devoir_soumissiondevoir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='soumissiondevoir',
            name='soumissiondevoir_unique_devoir_etudiant',
        ),
        migrations.AlterUniqueTogether(
            name='soumissiondevoir',
            unique_together={('devoir', 'etudiant')},
        ),
    ]
