# Generated by Django 6.0.2 on 2026-02-05 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0006_remove_soumissiondevoir_soumissiondevoir_unique_devoir_etudiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='support_cours',
            field=models.ForeignKey(blank=True, help_text='Support de cours associé (TD ou TP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoirs', to='academique.supportcours'),
        ),
    ]
