# Generated by Django 6.0.2 on 2026-02-05 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0007_devoir_support_cours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoumissionTDTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='soumissions_tdtp/')),
                ('format_fichier', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel (.xlsx, .xls)'), ('WORD', 'Word (.docx, .doc)')], default='PDF', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('feedback_professeur', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SOUMIS', 'Soumis'), ('CORRIGE', 'Corrigé'), ('NOTE', 'Noté')], default='EN_ATTENTE', max_length=20)),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_tdtp', to=settings.AUTH_USER_MODEL)),
                ('support_cours', models.ForeignKey(limit_choices_to={'type_support__in': ['TD', 'TP']}, on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_tdtp', to='academique.supportcours')),
            ],
            options={
                'unique_together': {('support_cours', 'etudiant')},
            },
        ),
    ]
