# Generated by Django 6.0.2 on 2026-02-08 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0010_alter_cours_id_alter_cycle_id_alter_devoir_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('cible', models.CharField(choices=[('TOUS', 'Tout le monde'), ('ETUDIANTS', 'Étudiants uniquement'), ('PROFESSEURS', 'Professeurs uniquement')], default='TOUS', max_length=20)),
                ('important', models.BooleanField(default=False, help_text='Épingler cette annonce')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
